### ISSUE TITLE
No module named 'custom_components.binance'

### ISSUE THREAD

**Issue by Tony2k** [Kartax/home-assistant-binance#3]
In sensors.yaml I added 

`  - platform: binance
    symbols:
      - BTCUSDT
      - ETHUSDT`

but on reboot I have error: Configuration is not valid: Platform error sensor.binance - No module named 'custom_components.binance'

**Comment by Kartax** [comment]
It seems that the integration has not been installed.
Please make sure to

- first install it via HACS
- then reboot HA
- then add the configuration
- then reboot HA again

**Comment by Tony2k** [comment]
Now works! I removed one sensor but the entity is still present, how can I delete it?

**Comment by Tony2k** [comment]
Now works, thanks!
