### ISSUE TITLE
add define the number of decimal places for the displayed value

### ISSUE THREAD

**Issue by AlexQuaken** [Kartax/home-assistant-binance#7]
Currently, when configuring sensors, there is no direct option to specify the number of decimal places for the displayed value. The default precision of 8 decimal places seems excessive for many use cases.

Feature Request:
Add an optional parameter in the sensor configuration to allow users to define the number of decimal places for the displayed value. This can provide more flexibility and control for users who want to customize the precision of the sensor readings.

![image](https://github.com/Kartax/home-assistant-binance/assets/61948337/0b8eddc9-14b5-4195-a3b4-45488429e4f0)

**Comment by Jurgen-DOUCHY** [comment]
+1

**Comment by LurchiStromberg** [comment]
Somebody found a Solution to reduce decimal Spaces to 2 ?

**Comment by Kartax** [comment]
Not sure when i will have the time to work on that.
For now, you could use custom-entity-row. It allows defining a precision.

<img width="984" alt="image" src="https://github.com/Kartax/home-assistant-binance/assets/24891257/250925fa-98f6-435e-ae0c-554d6140884d">

**Comment by LurchiStromberg** [comment]
Hi!
If i put this in my configuration.yaml

![2024-03-13 13_21_40-configuration yaml -  D__FlashFXP_Cache_~flashfxp_34CCB8B0_edit tmp_configuratio](https://github.com/Kartax/home-assistant-binance/assets/30866642/6f4f76a4-4754-4013-8caf-34f370dc05c8)

I get this Error:

![2024-03-13 13_22_37-Entwicklerwerkzeuge – Home Assistant und 16 weitere Seiten - Persönlich – Micros](https://github.com/Kartax/home-assistant-binance/assets/30866642/70a47cd4-39f9-451e-a393-078c7e37727d)

**Comment by Kartax** [comment]
This is not how it works :-) Your configuratin.yaml stays as before - so just the sensor with the desired symbols.

My code snippet shows the configuration of a card in the frontend and makes use of the custom card [multiple-entity-row](https://github.com/benct/lovelace-multiple-entity-row)

**Comment by Kartax** [comment]
I created a new Version [1.1.4](https://github.com/Kartax/home-assistant-binance/releases/tag/1.1.4)

There you can define the number of decimals:

<img width="209" alt="image" src="https://github.com/Kartax/home-assistant-binance/assets/24891257/e7a930ef-b775-42ea-bd33-08c2f52ea66b">

**Comment by LurchiStromberg** [comment]
Thank you!
Will it be available at HACS?

**Comment by Kartax** [comment]
It already is
